CALL CSVWRITE('/path/to/output/VST3.csv',
'WITH FilteredClones AS (
    SELECT
        FUNCTION_ID_ONE,
        FUNCTION_ID_TWO,
        FUNCTIONALITY_ID,
        SYNTACTIC_TYPE,
        SIMILARITY_LINE,
        SIMILARITY_TOKEN
    FROM CLONES
    WHERE SYNTACTIC_TYPE = 3
        AND SIMILARITY_LINE >= 0.9 AND SIMILARITY_LINE < 1.0
        AND MIN_JUDGES >= 2
        AND MIN_CONFIDENCE >= 2
    ORDER BY RANDOM()
    LIMIT 500
)
SELECT
    fc.FUNCTION_ID_ONE,
    fc.FUNCTION_ID_TWO,
    f1.NAME AS FUNCTION_ONE_NAME,
    f1.TYPE AS FUNCTION_ONE_TYPE,
    f1.STARTLINE AS FUNCTION_ONE_STARTLINE,
    f1.ENDLINE AS FUNCTION_ONE_ENDLINE,
    f2.NAME AS FUNCTION_TWO_NAME,
    f2.TYPE AS FUNCTION_TWO_TYPE,
    f2.STARTLINE AS FUNCTION_TWO_STARTLINE,
    f2.ENDLINE AS FUNCTION_TWO_ENDLINE,
    fc.FUNCTIONALITY_ID,
    fc.SYNTACTIC_TYPE,
    fc.SIMILARITY_LINE,
    fc.SIMILARITY_TOKEN
FROM FilteredClones fc
JOIN FUNCTIONS f1 ON fc.FUNCTION_ID_ONE = f1.ID
JOIN FUNCTIONS f2 ON fc.FUNCTION_ID_TWO = f2.ID;');
